#ifndef PLAYSTATION_CONTROLLER_DRIVERS__VISIBILITY_CONTROL_H_
#define PLAYSTATION_CONTROLLER_DRIVERS__VISIBILITY_CONTROL_H_

// This logic was borrowed (then namespaced) from the examples on the gcc wiki:
//     https://gcc.gnu.org/wiki/Visibility

#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define PLAYSTATION_CONTROLLER_DRIVERS_EXPORT __attribute__ ((dllexport))
    #define PLAYSTATION_CONTROLLER_DRIVERS_IMPORT __attribute__ ((dllimport))
  #else
    #define PLAYSTATION_CONTROLLER_DRIVERS_EXPORT __declspec(dllexport)
    #define PLAYSTATION_CONTROLLER_DRIVERS_IMPORT __declspec(dllimport)
  #endif
  #ifdef PLAYSTATION_CONTROLLER_DRIVERS_BUILDING_LIBRARY
    #define PLAYSTATION_CONTROLLER_DRIVERS_PUBLIC PLAYSTATION_CONTROLLER_DRIVERS_EXPORT
  #else
    #define PLAYSTATION_CONTROLLER_DRIVERS_PUBLIC PLAYSTATION_CONTROLLER_DRIVERS_IMPORT
  #endif
  #define PLAYSTATION_CONTROLLER_DRIVERS_PUBLIC_TYPE PLAYSTATION_CONTROLLER_DRIVERS_PUBLIC
  #define PLAYSTATION_CONTROLLER_DRIVERS_LOCAL
#else
  #define PLAYSTATION_CONTROLLER_DRIVERS_EXPORT __attribute__ ((visibility("default")))
  #define PLAYSTATION_CONTROLLER_DRIVERS_IMPORT
  #if __GNUC__ >= 4
    #define PLAYSTATION_CONTROLLER_DRIVERS_PUBLIC __attribute__ ((visibility("default")))
    #define PLAYSTATION_CONTROLLER_DRIVERS_LOCAL  __attribute__ ((visibility("hidden")))
  #else
    #define PLAYSTATION_CONTROLLER_DRIVERS_PUBLIC
    #define PLAYSTATION_CONTROLLER_DRIVERS_LOCAL
  #endif
  #define PLAYSTATION_CONTROLLER_DRIVERS_PUBLIC_TYPE
#endif

#endif  // PLAYSTATION_CONTROLLER_DRIVERS__VISIBILITY_CONTROL_H_
